<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search bdresurs
    </h1>
    <p>
        <?php echo $this->tag->linkTo(array("bdresurs/new", "Create bdresurs")) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        array(
            "bdresurs/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldText" class="col-sm-2 control-label">Text</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("text", "size" => 30, "class" => "form-control", "id" => "fieldText")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdResursa" class="col-sm-2 control-label">Id Of Resursa</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("id_resursa", "type" => "number", "class" => "form-control", "id" => "fieldIdResursa")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldModeratorIdM" class="col-sm-2 control-label">Moderator Of Id Of M</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("moderator_id_m", "type" => "number", "class" => "form-control", "id" => "fieldModeratorIdM")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldBdIdMarshruta" class="col-sm-2 control-label">BD Of Id Of Marshruta</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("BD_id_marshruta", "type" => "number", "class" => "form-control", "id" => "fieldBdIdMarshruta")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldBdIdResursa" class="col-sm-2 control-label">BD Of Id Of Resursa</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("BD_id_resursa", "type" => "number", "class" => "form-control", "id" => "fieldBdIdResursa")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAud" class="col-sm-2 control-label">Aud</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("aud", "size" => 30, "class" => "form-control", "id" => "fieldAud")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldRemont" class="col-sm-2 control-label">Remont</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("remont", "size" => 30, "class" => "form-control", "id" => "fieldRemont")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Search", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
