<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("bdresurs", "Go Back")) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create bdresurs
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "bdresurs/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>




<div class="form-group">
    <label for="fieldAud" class="col-sm-2 control-label">Аудитория</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("aud", "size" => 30, "class" => "form-control", "id" => "fieldAud")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldRemont" class="col-sm-2 control-label">Состояние</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("remont", "size" => 30, "class" => "form-control", "id" => "fieldRemont")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldText" class="col-sm-2 control-label">Комментарии</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("text", "size" => 30, "class" => "form-control", "id" => "fieldText")) ?>
    </div>
</div>




<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Save", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
