<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("bdresurs/index", "Go Back")); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(array("bdresurs/new", "Create ")); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Text</th>
            <th>Id Of Resursa</th>
            <th>Moderator Of Id Of M</th>
            <th>BD Of Id Of Marshruta</th>
            <th>BD Of Id Of Resursa</th>
            <th>Aud</th>
            <th>Remont</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $bdresur): ?>
            <tr>
                <td><?php echo $bdresur->text ?></td>
            <td><?php echo $bdresur->id_resursa ?></td>
            <td><?php echo $bdresur->moderator_id_m ?></td>
            <td><?php echo $bdresur->BD_id_marshruta ?></td>
            <td><?php echo $bdresur->BD_id_resursa ?></td>
            <td><?php echo $bdresur->aud ?></td>
            <td><?php echo $bdresur->remont ?></td>

                <td><?php echo $this->tag->linkTo(array("bdresurs/edit/" . $bdresur->text, "Edit")); ?></td>
                <td><?php echo $this->tag->linkTo(array("bdresurs/delete/" . $bdresur->text, "Delete")); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("bdresurs/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("bdresurs/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("bdresurs/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("bdresurs/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
