<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Поиск
    </h1>
 
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        array(
            "bdresurss/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldIdResursa" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("id_resursa", "type" => "number", "class" => "form-control", "id" => "fieldIdResursa")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAud" class="col-sm-2 control-label">Аудитория</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("aud", "size" => 30, "class" => "form-control", "id" => "fieldAud")) ?>
    </div>
</div>




<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Search", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
