<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("bdresurss/index", "Go Back")); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(array("bdresurss/new", "Create ")); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Поиск информации по ресурсам</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Аудитория</th>
            <th>Состояние</th>
            <th>Комментарии</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $bdresurs): ?>
            <tr>
                <td><?php echo $bdresurs->id_resursa ?></td>
            <td><?php echo $bdresurs->aud ?></td>
            <td><?php echo $bdresurs->remont ?></td>
            <td><?php echo $bdresurs->text ?></td>

                <td><?php echo $this->tag->linkTo(array("bdresurss/edit/" . $bdresurs->id_resursa, "Edit")); ?></td>
                <td><?php echo $this->tag->linkTo(array("bdresurss/delete/" . $bdresurs->id_resursa, "Delete")); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("bdresurss/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("bdresurss/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("bdresurss/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("bdresurss/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
