<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("bd_marshrut", "Go Back")) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Прокладка маршрута в ГЗ
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "bd_marshrut/lite",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

 

<div class="form-group">
    <label for="fieldB" class="col-sm-2 control-label">Аудитория</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("B", "size" => 30, "class" => "form-control", "id" => "fieldB")) ?>
         <?php echo $this->tag->submitButton(array("Проложить маршрут", "class" => "btn btn-default")) ?>
    </div>
</div>

 

<?php echo $this->tag->endForm(); ?>
