<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("bd_marshrut/index", "Go Back")); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(array("bd_marshrut/new", "Create ")); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id Of Marshruta</th>
            <th>Username</th>
            <th>Name</th>
            <th>A</th>
            <th>B</th>
            <th>Text</th>
            <th>Id</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $bd_marshrut): ?>
            <tr>
                <td><?php echo $bd_marshrut->id_marshruta ?></td>
            <td><?php echo $bd_marshrut->username ?></td>
            <td><?php echo $bd_marshrut->name ?></td>
            <td><?php echo $bd_marshrut->A ?></td>
            <td><?php echo $bd_marshrut->B ?></td>
            <td><?php echo $bd_marshrut->text ?></td>
            <td><?php echo $bd_marshrut->id ?></td>

                <td><?php echo $this->tag->linkTo(array("bd_marshrut/edit/" . $bd_marshrut->id_marshruta, "Edit")); ?></td>
                <td><?php echo $this->tag->linkTo(array("bd_marshrut/delete/" . $bd_marshrut->id_marshruta, "Delete")); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("bd_marshrut/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("bd_marshrut/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("bd_marshrut/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("bd_marshrut/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
