<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("bd", "Go Back")) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create bd
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "bd/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldIdMarshruta" class="col-sm-2 control-label">Id Of Marshruta</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("id_marshruta", "type" => "number", "class" => "form-control", "id" => "fieldIdMarshruta")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdResursa" class="col-sm-2 control-label">Id Of Resursa</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("id_resursa", "type" => "number", "class" => "form-control", "id" => "fieldIdResursa")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Save", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
